version: "3.7"

services:
  database_drr:
    image: postgres
    container_name: database_drr
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
